
## 项目合作合同范本  

## [篇一：项目投资合作协议书范本]  

甲方： 乙方：  

以上各方共同投资人(以下简称“共同投资人”)经友好协商，根据中华人民共和国法律、法规的规定，双方本着互惠互利的原则，就甲乙双方合作投资项目事宜达成如下协议，以共同遵守。第一条共同投资人的投资额和投资方式  

甲、乙双方同意，以双方注册成立的公司(以下简称)为项目投资主体。  

各方出资分别：甲方占出资总额的 %；乙方占出资总额的 %。  

第二条利润分享和亏损分担  

共同投资人按其出资额占出资总额的比例分享共同投资的利润，分担共同投资的亏损。项目合作合同范本。  

共同投资人各自以其出资额为限对共同投资承担责任，共同投资人以其出资总额为限对股份有限公司承担责任。  

共同投资人的出资形成的股份及其擎生物为共同投资人的共有财产，由共同投资人按其出资比例共有。  

共同投资于股份有限公司的股份转让后，各共同投资人有权按其出资比例取得财产。  

第三条事务执行  

1. 共同投资人委托甲方代表全体共同投资人执行共同投资的日常事务，包括但不限于：  

(1)在股份公司发起设立阶段，行使及履行作为股份有限公司发起人的权利和义务；  

(2)在股份公司成立后，行使其作为股份公司股东的权利、履行相应义务；  

(3)收集共同投资所产生的擎息，并按照本协议有关规定处置；  

2. 其他投资人有权检查日常事务的执行情况，甲方有义务向其他投资人报告共同投资的经营状况和财务状况；  

3. 甲方执行共同投资事务所产生的收益归全体共同投资人，所产生的亏损或者民事责任，由共同投资人承担；  

4. 项目合作合同范本。甲方在执行事务时如因其过失或不遵守本协议而造成其他共同投资人损失时，应承担赔偿责任；  

5. 共同投资人可以对甲方执行共同投资事务提出异议。提出异议时，应暂停该项事务的执行。如果发生争议，由全体共同投资人共同决定。  

6. 共同投资的下列事务必须经全体共同投资人同意：  

(1)转让共同投资于股份有限公司的股份；  

(2)以上述股份对外出资；  

(3)更换事务执行人。  

第四条投资的转让  

1. 共同投资人向共同投资人以外的人转让其在共同投资中的全部或部分出资额时，须经全部共同投资人同意；  

2. 共同投资人之间转让在共同投资中的全部或部分投资额时，应当通知其他共同出资人；  

3. 共同投资人依法转让其出资额的，在同等条件下，其他共同投资人有优先受让的权利。  

第五条其他权利和义务  

1. 甲方及其他共同投资人不得私自转让或者处分共同投资的股份；2. 共同投资人在股份有限公司登记之日起三年内，不得转让其持有的股份及出资额；  

3. 股份有限公司成立后，任一共同投资人不得从共同投资中抽回出资额；4. 股份有限公司不能成立时，对设立行为所产生的债务和费用按各共同投资人的出资比例分担。

<--- Page Split --->

第六条违约责任  

为保证本协议的实际履行，甲方自愿提供其所有的向其他共同投资人提供担保。甲方承诺在其违约并造成其他共同投资人损失的情况下，以上述财产向其他共同投资人承担违约责任。  

第七条其他  

1. 本协议未尽事宜由共同投资人协商一致后，另行签订补充协议。  

2. 本协议经全体共同投资人签字盖章后即生效。本协议一式 份，共同投资人各执一份。  

甲方(签字)： 乙方(签字)：  

年 月 日 年 月 日签订地点：  

签订地点：  

## [篇二：工程项目施工合作协议书范本]  

甲方： （以下简称甲方）  

乙方： （以下简称乙方）  

经协商，甲乙双方就合作施工合同工程施工事宜达成一致意见，以便共同遵守。  

第一条工程实施责任及要求  

1、甲方将主合同项下全部工程的实施责任交乙方承担(包括该合同项下的全部变更工程)。  

2、工期、质量必须满足主合同要求。  

第二条甲方责任  

1、负责及时办理主合同的预付款手续。  

2、负责为乙方实施主合同提供相应的授权，解决只能由甲方解决的事项。  

3、负责沿线地方政府的协调工作及本工程的通知、图纸等。  

第三条乙方责任  

1、负责代甲方履行主合同的施工、缺陷修复及保修责任。  

2、负责以自身资源按照主合同要求完成该工程，自担风险、自负盈亏。  

3、自觉接受甲方的各项监督检查。  

4、保证不以甲方或项目部的名义从事于本工程无关的活动。  

5、负责及时清偿为实施本工程而产生的各类债务，及时支付民工工资。  

第四条费用、结算与支付  

1、本工程采用包工包料包安全的方式，一次包干价：1965042。2元，按甲方给乙方提供的图纸所注明的工程量，超出图纸部分另行计算。  

2、经双方协商，乙方开工之日起一个月内，甲方开始支付乙方工程款，按实际完成工程量支付(基础完工后付工程总造价的 \(10\%\) ，一层封顶付总造价的 \(20\%\) ，二层封顶付总造价的 \(20\%\) ，封顶付总造价的 \(20\%\) ，内外粉刷时付 \(10\%\) ，工程竣工付 \(15\%\) ，余款 \(5\%\) 工程完工后一年内付清)  

第五条违约责任  

1、对于主合同所规定的甲方的合同责任，如因甲方工程款支付不及时造成停工引起的损失由甲方承担一切责任。双方按本协议规定的各自的责任分别承担。若由于自身原因造成违约，违约方不得要求另一方共同承担违约责任。  

2、工期5个月，质量达到合格标准。

<--- Page Split --->

3、由于乙方自身原因产生安全事故，导致乙方、甲方或第三方人身财产受损，乙方须自费承担事故处理费用，向受损方赔偿。  

第六条其他未尽事宜，双方友好协商，并签订补充协议。补充协议作为本协议的补充，不得与本协议相抵触，应与本协议一起共同执行。  

第七条附则  

1、本协议经双方签字盖章后生效。履行完协议约定的全部义务、工程竣工验收合格，保修期满，结清各项费用后终止。  

2、本协议一式三份。甲方二份，乙方一份。  

甲方：（盖章） 乙方：（盖章）  

代表： 代表：  

住所：  

身份证号码：  

日期： 年 月 日  

## [篇三：房地产开发建设项目合作协议书范本]  

甲方： 法定地址：  

乙方： 法定地址：  

依据中华人民共和国合同法及有关法律法规的规定，甲、乙双方本着平等互利、诚实信用的原则，共同合作参与开发建设房地产项目，为明确甲、乙双方的权利、义务和责任，经过友好协商，达成如下合作协议，共同遵守执行：  

## 一、合作项目概况  

甲、乙双方初步商定本次合作为大河粮站房地产开发建设，  

项目地址：  

占地面积： 平方米  

## 二、合作的范围及内容  

根据甲乙双方协商本次合作模式为资产置换模式，甲方以南江县大河镇大  

河粮油购销公司土地共 平方米，双方约定价格共计 元作为本次项目置换房屋，待乙方规划设计完成后甲方一次性抵扣完土地金额，具体如附件2。  

根据目前的实际情况和市场状况，双方商定本次合同为本项目建设的初期合同，到项目可以开工建设时再签订正式合同，本次合作范围及内容是为本项目前期的规划、设计及相关事项，包括项目开发建设所需资金及销售。  

## 三、合作方式  

在本次共同合作中，前期以甲方的名义进行对外沟通、信息交流、协调关系、公关等商务事宜，乙方以甲方管理人员的身份完成本协议约定的工作，进行相应合法商务活动。  

## 四、甲、乙双方的工作与责任  

## 4.1、甲方责任：  

4.1.1、向乙方提供项目活动所必需的一切相关资料，如甲方的土地使用证、组织机构、管理机构、注册资本、企业章程、企业营业执照、资质证书、验资报告、年度财务报表、法人代表证明书、授权委托书等一切为合作项目服务的资料证明文件。

<--- Page Split --->

4.1.2、在乙方提供投资开发所必须的资料基础上，负责协助乙方筹备项目的推介及开发所需的文件资料(包括老百姓的拆迁，项目开发必须的土地、建设手续，协调周边相邻关系)  

4.2.4、负责协调关系并使乙方在合作开发的项目竞争中入围中标。  

4.2、乙方责任：  

4.1.6、承担本项目合作过程中所发生的一切费用支出。  

4.2.1、负责提供获得项目服务事宜的公共关系支持。  

4.2.2、负责办理项目服务所需的全部基本资料。  

4.2.5、双方商定的其他工作。  

五、保证与承诺  

5.1、双方有权签订并执行本协议约定的义务，并且无需任何其他人的同意。  

5.2、双方所提供的任何资料、信息、数据、文件等均是最新的、客观的、真实的、完整的，并且不存在任何虚假、侵权、故意疏忽或虚伪陈述。  

5.3、双方将所知悉的可能影响本协议的所有事项(如果有)尽快通知对方，并提示对方注意。  

5.4、乙方在提出正当的合法商务活动时，甲方应积极的给予支持，  

六、合作期限  

本协议有效期暂定为两年，若合作项目没有任何进展则经甲、乙双方签字盖章之日生效起的两年年后终止，若合作项目进展顺利，乙方在合作开发的项目竞争中入围中标，则本协议有效期延长至合作项目销售封盘为止。  

## 七、违约责任  

7.1、因本协议是在项目开发前期签订的(未立项，未规划，未设计及其他相关手续)所以若单方违约，须承担此次项目另一方开支费用的四倍。  

7.1、由于任何一方所无法控制的原因，包括战争、火灾、风暴、政治封锁或自然灾害而导致其无法履行协议义务时，该方不承担违约责任，亦不对另一方因上述不履行而导致的任何损失或损坏承担责任。  

## 八、适用法律  

8.1、本协议的订立、效力、解释和履行，均适用于中华人民共和国的法律。  

8.2、如果双方对本协议的效力、解释或履行发生任何争议，各方首先应通过友好协商。自争议发生之日起三十日内协商解决不成，则任何一方均有权向项目所在地法院提起诉讼。  

8.3、除有关争议的条款外，在争议的解决期间，不影响本协议其他条款的继续履行。  

8.4、本协议部分条款依法或依本协议的规定终止效力或被宣告无效的，不影响本协议其他条款的效力。  

九、协议的生效、协议的修改、变更、补充及其它  

9.1、本协议经甲、乙双方盖章、签字后生效。  

9.2、本协议一经生效即受法律保护，任何一方不得擅自修改、变更和补充。本协议的任何修改、变更和补充均需经双方协商一致，达成书面协议。  

9.3、本协议以中文写成，正本一式四份，甲、乙双方各执两份，具有同等法律效力。  

9.4、与本协议有关的任何往来文件均作为本协议附件，与本协议具有同等法律效力。  

9.5、本协议于 年 月 日在 正式签署。  

甲方(盖章)： 乙方(盖章)：  

法定代表人(签字或盖章)： 法定代表人(签字或盖章)：  

或授权代表(签字)： 或授权代表(签字)：

<--- Page Split --->

## [篇四:项目合作协议书范本]  

甲方:北京市xxx有限公司  

乙方:xx市xxx有限公司  

甲、乙双方本着诚信、互利的原则,就甲方产业项目合作开发达成如下合作意向:  

## 一、项目内容简介  

1、开发项目名称:  

2、乙方合作意向:  

3、乙方合作方式:  

## 二、甲方的权利和义务  

1、甲方负责项目的规划、设计、可行性研究等前期准备工作;  

2、甲方负责项目的报建报批手续;  

3、甲方负责项目征地的相关手续;  

4、甲方负责向政府争取项目可争取到的优惠政策;  

5、如项目是甲、乙双方合资建设,甲方享有对项目建设合程管理的权利;项目建成后甲方享有相对应的利润分配;  

6、如项目是乙方独资建设,甲方对项目建设中的乙方实施情况享有建议权、审议权和监督权。  

## 三、乙方的权利和义务  

1、乙方根据项目投资要注,负责资金落实到位;  

2、乙方根据项目的规划和设计要求,负责对项目建设的组织和实施;  

3、在项目建设正式协议书签定之前,乙方享有对该项目咨询、论证、实地考察的权利,甲方应给予积极支持与配合;  

4、如项目是甲、乙双方合资建设,乙方享有相对应的利润分配。  

## 四、其他事宜  

1、该协议书仅为合作意向,其合作方式,投资客度等待双方进一步考察协商后,签定正式<项目合作协议书>;  

2、甲、乙双方的责、权、利在<项目合作协议书>中作全面的约定;  

3、甲、乙双方保证所提供的资料真实、有效、合法。  

甲方:北京市xxx有限公司乙方:xx市xxx有限公司  

(签章)  

日期:年_月_日日期:年_月_日

<--- Page Split --->
